### PR TITLE
Refactor Terminator plugin structure and enhance command functionality

### PR DESCRIPTION
**Pull request by Mardssss**
- Refactored code by separating concerns into distinct classes:
  - CommandClass: Handles command operations.
  - ListenerClass: Manages event listening.
  - ItemBuilderClass: Constructs and returns the Terminator item stack.
  - UtilsClass: Provides utilities, such as string color code conversion.
- Modified the main command to `/terminator getitem` for clarity.
- Enhanced documentation with JavaDoc comments for better maintainability and readability.

Questions for discussion:
1. Why is the Terminator item only usable by players?
2. What are the current project goals, and how can I contribute further to meet them?
You can contact me on discord mard2364

### CODE REVIEW

**Comment by Mitra-88** [comment]
thanks for opening this pr :)
i appreciate you taking the time to help out with the plugin

answering your questions:

1. i dont really understand your question, but i think thats how it should work?
2. i dont think there is anything left, other than porting the plugin to newer versions

**Comment by Mardssss** [comment]
You're welcome.
Clarification of Question:

At the moment, only operators (OP) are able to use the command /terminator getitem, which grants them access to the Terminator bow. I would like to know the reasoning behind this decision—why isn't this command available to all players?

Recommendation: We could provide a configuration file (config.yml) that lets server administrators control who can get the Terminator item in order to give the plugin more flexibility. This could contain configurations for:

Which players (e.g., all players, just OPs, particular list of players) can carry out the command?
The Terminator bow's customizable features include damage, durability, and special effects etc..

I look forward to hearing your opinions on this!

**Comment by Mitra-88** [comment]
1. I'm not sure why I did that, but you can make it available for everyone. I wasn't planning to add it, but I just added it anyway because I thought that's what players wanted, but I guess I was wrong.

2. I don't really think I'm too interested in the config.yml idea. It's cool, but I think it's unnecessary for this plugin.

**Comment by Mitra-88** [comment]
The only problem I'm facing right now is that I'm not sure how to make it work when you have arrows in your inventory or in gamemode 1. The current workaround is to shoot arrows by left-clicking.

**Comment by Mardssss** [comment]
ah ok, you want to check if the player is in survival, if it is then every time we shoot we remove the arrow or arrows from its inventory
```
@EventHandler
public void onPlayerInteract(PlayerInteractEvent event) {
    Player player = event.getPlayer();
    ItemStack item = event.getItem();

    if (item == null || !item.hasItemMeta()) {
        return;
    }

    ItemMeta meta = item.getItemMeta();
    if (!Objects.requireNonNull(meta).hasDisplayName() || !meta.getDisplayName().equals(ChatColor.LIGHT_PURPLE + "Hasty Terminator " + ChatColor.GOLD + "✪✪✪✪" + ChatColor.RED + "➎")) {
        return;
    }

    if (!CLICK_ACTIONS.contains(event.getAction())) {
        return;
    }

    // Check if the player is in survival mode
    if (player.getGameMode() == GameMode.SURVIVAL) {
        // Remove arrows from the player's inventory
        player.getInventory().removeItem(new ItemStack(Material.ARROW));
    }

    event.setCancelled(true);

    new BukkitRunnable() {
        @Override
        public void run() {
            Vector forward = player.getLocation().getDirection();
            Vector right = forward.clone().rotateAroundY(Math.toRadians(15));
            Vector left = forward.clone().rotateAroundY(Math.toRadians(-15));

            shootArrow(player, forward);
            shootArrow(player, right);
            shootArrow(player, left);
        }
    }.runTask(plugin);
}
```

**Comment by Mitra-88** [comment]
Something like that. The problem is that the bow charges the attack, which is not what I wanted since it's a shortbow—it should shoot instantly.

**Comment by Mardssss** [comment]
> Something like that. The problem is that the bow charges the attack, which is not what I wanted since it's a shortbow—it should shoot instantly.

what do you mean? what realy is the issue?
#

Do you ill merge my pull request into the main repo?
#
by the way how you did the stats on your aboutme page?

**Comment by Mitra-88** [comment]
1. did you play hypixel skyblock? a shortbow shoots instantly but the problem I'm facing is that when the players has arrows in their inventory or in gamemode 1 the bow charges the attack

2. yes sorry :)

3. from [here](https://gprm.itsvg.in/) but i made some modifications

**Pull request merged**
